version: "3.7"
services:
  app:
    container_name: "hapiline_app"
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3333:3333"
      - "4444:4444"
    volumes:
      - .:/usr/src/app
  mailhog:
    container_name: "hapiline_mailhog"
    build:
      context: .
      dockerfile: Dockerfile-mailhog
    ports:
      - 1025:1025
      - 8025:8025
  db:
    container_name: "hapiline_db"
    restart: always
    image: "postgres:11.5-alpine"
    volumes:
      - ./data/postgre/db:/data/db
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.env-docker
